# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - DataSyncV2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  install:
      steps:
      - name: Install dependencies 1
        run : mvn org.apache.maven.plugins:maven-install-plugin:2.5.1:install-file \
-Dfile=lib/force-wsc-57.0.0-uber.jar \
-DlocalRepositoryPath=lib

      - name: Install dependencies 2
        run : mvn org.apache.maven.plugins:maven-install-plugin:2.5.1:install-file \
-Dfile=lib/opencsv-5.7.1.jar \
-DlocalRepositoryPath=lib

  build:
    runs-on: windows-latest

      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'DataSyncV2'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_42AD0A8EAB754BCC9A52996202926569 }}
          package: '*.jar'
